name: Call a reusable workflow

on:
  push:
    branches:
      - main
      - staging
      - migration

jobs:
  Deployment:
    uses: luciocarvalhojr/tm-workflow/.github/workflows/deploy-ssm.yml@v1.0.0
    with:
      environment: >-
        ${{ github.ref_name == 'main' && 'production'
            || github.ref_name == 'staging' && 'staging'
            || github.ref_name == 'migration' && 'migration'
        }}
    secrets: 
      aws-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
