name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: luciocarvalhojr/tm-workflow/.github/workflows/deploy-ssm.yml@main
    with:
      config-path: .github/labeler.yml
      aws-access-key-id: ABC-123
    secrets:
      token: ${{ secrets.MY_SECRET }}
      aws-access-key-id: ABC123
