name: Call a reusable workflow

on:
  push:
    branches:
      - main
      - staging
      - migration

jobs:
  Deployment:
    uses: luciocarvalhojr/tm-workflow/.github/workflows/deploy-ssm.yml@main
    with:
      environment: >-
        ${{ github.ref_name == 'main' && 'production'
            || github.ref_name == 'staging' && 'staging'
            || github.ref_name == 'migration' && 'migration'
        }}
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.MY_SECRET }}
